server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/java_demo_0005?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: UTC

mybatis:
  mapper-locations:
    - classpath:mapper/*Mapper.xml
    - classpath*:cn/**/mapper/*.xml
  type-aliases-package: cn.sichu.demo.entity
  configuration:
    map-underscore-to-camel-case: true

utils:
  #工作机器ID
  workerId: 5
  #序列号
  datacenterId: 10

logging:
  level:
    org.springframework.web: ERROR
    cn.sichu.demo: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: C:/Users/sichu/dev/logs/mylog.log
